apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: telegram-f5-bot-token
  namespace: kagent
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: telegram-f5-bot-token
    creationPolicy: Owner
  data:
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: secret/telegram
        property: f5aikagentbot_key
