apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentgateway-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ProfessorSeb/k8s-iceman.git
    targetRevision: main
    path: manifests/agentgateway-config
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
